# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
# pip install tensorflow

In [2]:
# your code here
import pandas as pd
import numpy as np

# Keras currently only runs in python 3.6!
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# from Sklearn
from sklearn.model_selection import train_test_split

In [3]:
# your code here
tic_tac_toe = pd.read_csv('tic-tac-toe.csv')
tic_tac_toe.replace('x', 0, inplace = True)
tic_tac_toe.replace('o', 1, inplace = True)
tic_tac_toe.replace('b', -1, inplace = True)

In [4]:
tic_tac_toe.head()

TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   0   0   0   0   1   1   0   1   1   True
1   0   0   0   0   1   1   1   0   1   True
2   0   0   0   0   1   1   1   1   0   True
3   0   0   0   0   1   1   1  -1  -1   True
4   0   0   0   0   1   1  -1   1  -1   True

In [22]:
tic_tac_toe.size

9580

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [5]:
tic_tac_toe.columns

Index(['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR', 'class'], dtype='object')

In [6]:
X = np.array(tic_tac_toe.drop(labels='class', axis = 1))
y = np.array(tic_tac_toe['class'])

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=29)

In [29]:
X_train

array([[ 1,  0,  0, ...,  0, -1,  1],
       [ 0,  1,  1, ...,  0,  1, -1],
       [ 0,  0,  1, ..., -1,  0,  0],
       ...,
       [-1,  0,  1, ...,  0,  0,  0],
       [ 0, -1,  0, ...,  0,  1,  1],
       [ 1,  1,  0, ...,  0,  0,  1]], dtype=int64)

In [30]:
X_test

array([[ 0,  0, -1, ..., -1,  0, -1],
       [-1,  1,  0, ...,  0,  1, -1],
       [-1,  0,  1, ...,  0,  0,  1],
       ...,
       [ 1,  0,  1, ...,  1,  0,  0],
       [ 1,  1,  1, ...,  0, -1,  0],
       [ 0,  1, -1, ...,  0,  1,  1]], dtype=int64)

In [43]:
# Build the model
model = Sequential([ # as far as we know, all networks are sequential
  Dense(18, activation='relu'),
  Dense(18, activation='relu'),      # choosing relu instead of sigmoid, this is somewhat common
  Dense(2, activation='softmax'),   # the softmax actiavation is the last one to compensate for the high volume additions
])

# Compile the model
model.compile(
  optimizer='adam', #here we could use stochastic gradient descent, but adam is a de facto standard
  loss='categorical_crossentropy', #this is how we create the original blam to play the blame game
  metrics=['accuracy'],
)

# Train the model
history = model.fit(
  X_train,
  to_categorical(y_train), # just to make sure the outputs are not considered numeric (because, ya know, they are numbers...)
  epochs=50, 
  batch_size=40,
)

# Evaluate the model
model.evaluate(
  X_test,
  to_categorical(y_test)
)

Epoch 1/50
20/20 [==============================] - 1s 1ms/step - loss: 0.6430 - accuracy: 0.6514
Epoch 2/50
20/20 [==============================] - 0s 2ms/step - loss: 0.6261 - accuracy: 0.6606
Epoch 3/50
20/20 [==============================] - 0s 2ms/step - loss: 0.6120 - accuracy: 0.6684
Epoch 4/50
20/20 [==============================] - 0s 2ms/step - loss: 0.5995 - accuracy: 0.6710
Epoch 5/50
20/20 [==============================] - 0s 2ms/step - loss: 0.5883 - accuracy: 0.6762
Epoch 6/50
20/20 [==============================] - 0s 2ms/step - loss: 0.5772 - accuracy: 0.6919
Epoch 7/50
20/20 [==============================] - 0s 2ms/step - loss: 0.5661 - accuracy: 0.6958
Epoch 8/50
20/20 [==============================] - 0s 2ms/step - loss: 0.5560 - accuracy: 0.7037
Epoch 9/50
20/20 [==============================] - 0s 2ms/step - loss: 0.5460 - accuracy: 0.7141
Epoch 10/50
20/20 [==============================] - 0s 2ms/step - loss: 0.5365 - accuracy: 0.7180
Epoch 11/50
20/20 [

[0.36603081226348877, 0.8177083134651184]

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [38]:
# your code here
predictions = model.predict(X_test[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) 

1/1 [==============================] - 0s 54ms/step
[0 1 1 1 0]


## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [44]:
# Yes. It had High loss and low accuracy...

# Build the model
model = Sequential([ # as far as we know, all networks are sequential
  Dense(18, activation='relu'),
  Dense(18, activation='relu'),      # choosing relu instead of sigmoid, this is somewhat common
  Dense(2, activation='softmax'),   # the softmax actiavation is the last one to compensate for the high volume additions
])

# Compile the model
model.compile(
  optimizer='adam', #here we could use stochastic gradient descent, but adam is a de facto standard
  loss='categorical_crossentropy', #this is how we create the original blam to play the blame game
  metrics=['accuracy'],
)

# Train the model  --  ADD MORE LAYERS
history = model.fit(
  X_train,
  to_categorical(y_train), # just to make sure the outputs are not considered numeric (because, ya know, they are numbers...)
  epochs=70, 
  batch_size=40,
)

# Evaluate the model
model.evaluate(
  X_test,
  to_categorical(y_test)
)

Epoch 1/70
20/20 [==============================] - 1s 2ms/step - loss: 0.6339 - accuracy: 0.6527
Epoch 2/70
20/20 [==============================] - 0s 1ms/step - loss: 0.6126 - accuracy: 0.6749
Epoch 3/70
20/20 [==============================] - 0s 2ms/step - loss: 0.5987 - accuracy: 0.6762
Epoch 4/70
20/20 [==============================] - 0s 2ms/step - loss: 0.5852 - accuracy: 0.6841
Epoch 5/70
20/20 [==============================] - 0s 1ms/step - loss: 0.5741 - accuracy: 0.6919
Epoch 6/70
20/20 [==============================] - 0s 2ms/step - loss: 0.5645 - accuracy: 0.6880
Epoch 7/70
20/20 [==============================] - 0s 2ms/step - loss: 0.5538 - accuracy: 0.7023
Epoch 8/70
20/20 [==============================] - 0s 2ms/step - loss: 0.5457 - accuracy: 0.7050
Epoch 9/70
20/20 [==============================] - 0s 2ms/step - loss: 0.5375 - accuracy: 0.7050
Epoch 10/70
20/20 [==============================] - 0s 2ms/step - loss: 0.5296 - accuracy: 0.7128
Epoch 11/70
20/20 [

[0.4171563684940338, 0.7760416865348816]

In [ ]:
#It improves but not that much ... how could I fix it?

**Which approach(es) did you find helpful to improve your model performance?**

In [9]:
# your answer here